Main 78988 install scripts dont handle errors from portal sdk
criticalmanufacturing/install-scripts pull request #17
Opened 2022-10-11 13:15 UTC by afjsilva

Update some documentation - domain, now doesn't exists. Updated queries on examples.
Add obsolete to domain params.
Added Try Catch clause when we perform some request to portalSDK and when the code can't continue (we have some exception from protal sdk) we log the exception and exit with code 1.
Change some Write-Debugs for Write-Host to inform the user what the script or portalSDK is doing.
Added -Force and -SecondsTimeout to runInitializeInfrastructures.ps1 (same on template).
- Force is to continue the Infrastructure creation when already exists the Infrastructure.
- Timeout is the seconds value to wait for Infrastructure creation to exists and be unlocked (default 180 seconds).

2022-10-19 16:39 UTC, EgzysT approved these changes
Looks good

2022-10-19 17:29 UTC, vitorpmoreira requested changes
Don't forget to update this branch with the changes from portalsdk: change the force flag and remove the timeout

2022-10-20 12:07 UTC, afjsilva commented
Merge with development branch done :)

2022-10-20 14:05 UTC, almeidev commented on utils/portal/deployAgent.ps1
> +    Write-Error "Probably was not possible to connect the Infrastructure Agent $agent! You must check and if necessary fix the connection."
Also, similarly to other scripts from us, explicitly `exit 1` in case of exception/error

2022-10-20 16:14 UTC, afjsilva commented
Suggestions applied with an additional single change on runInitializeInfrastructure (and template) - to print the url before try connect with the agent.

2022-10-20 17:16 UTC, vitorpmoreira reviewed
Shouldn't the target branch be the "development"?

2022-10-21 07:09 UTC, afjsilva commented
Changed and merged. No changes are made.

2022-10-25 15:08 UTC, vitorpmoreira requested changes

2022-10-25 15:08 UTC, vitorpmoreira commented on utils/portal/runInitializeInfrastructure.ps1
> +    Write-Host "Creating infrastructure..."
```suggestion
    Write-Host "Creating Customer Infrastructure..."
```

2022-10-25 15:08 UTC, vitorpmoreira commented on utils/portal/runInitializeInfrastructure.ps1
> +    Write-Host "Creating agent..."
```suggestion
    Write-Host "Creating Infrastructure Agent..."
```

2022-10-25 15:08 UTC, vitorpmoreira commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +    Write-Host "Creating infrastructure..."
```suggestion
    Write-Host "Creating Customer Infrastructure..."
```

2022-10-25 15:08 UTC, vitorpmoreira commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +    Write-Host "Creating agent..."
```suggestion
    Write-Host "Creating Infrastructure Agent..."
```

2022-10-25 16:39 UTC, afjsilva commented on utils/portal/runInitializeInfrastructure.ps1
> +    Write-Host "Login..."
Thx Vitor! I will change it :)

2022-10-25 16:45 UTC, afjsilva commented on utils/portal/runInitializeInfrastructure.ps1
> +# inform the user to proceed with the environment installation
The deployAgent can exit with code 1 if don't make the connection... If we don't log this URL before, we don't get the URL anymore and can configure or change anything right? I think this makes sense, but you are the expert xD

2022-10-25 17:01 UTC, vitorpmoreira commented on utils/portal/runInitializeInfrastructure.ps1
> +# inform the user to proceed with the environment installation
oh ok, but I fear that it will get lost in the logs... can you then make the change to log after or, in the case the deployAgent is exited with code 1, to also log it before exiting again?

2022-10-26 08:22 UTC, afjsilva commented on utils/portal/runInitializeInfrastructure.ps1
> +# inform the user to proceed with the environment installation
Yes :) I will try it

2022-10-26 10:09 UTC, vitorpmoreira requested changes

2022-10-26 10:09 UTC, vitorpmoreira commented on utils/portal/deployAgent.ps1
> +    [string]$url
This wasn't what I meant 😭 I mean't for you, in the other script, to get the exit code from this script and log the url nontheless. With this approach, you're tying this script to url that doesn't make sense to its functionality

2022-10-26 10:09 UTC, vitorpmoreira commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +. ./deployAgent.ps1 -agent $agent -url $url
you should get the exit code here instead of exiting right way and log the url nontheless.
it should be something like this (I did it from the top of my head, needs testing):
```suggestion
& . ./deployAgent.ps1 -agent $agent -url $url

# Inform the user to proceed with the environment installation
Write-Host $url

if ($LASTEXITCODE -eq 1) {
exit 1
}
```

2022-10-26 10:09 UTC, vitorpmoreira commented on utils/portal/deployAgent.ps1
> +    [string]$url
see the other comment

2022-10-26 10:12 UTC, almeidev commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +. ./deployAgent.ps1 -agent $agent -url $url
Or just forward the exit code from the operation after writing the url : `exit $LASTEXITCODE`

2022-10-26 10:41 UTC, afjsilva commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +. ./deployAgent.ps1 -agent $agent -url $url
Yup I think this suggestion from Nuno is better.
I will change it now :) thx to both <3

2022-10-26 11:30 UTC, afjsilva commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +. ./deployAgent.ps1 -agent $agent -url $url
I have a propmt if all goes ok, so I can't apply your suggestion Nuno. I applied something like the Vitor suggestion :) 
Thx to both again <3

2022-10-26 12:39 UTC, almeidev commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +Invoke-Expression $deployAgent
Didn't get the need to use Invoke-Expression instead of calling the script as before. What am I missing?

2022-10-26 13:00 UTC, vitorpmoreira commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +Invoke-Expression $deployAgent
Yes, @afjsilva you could have simply called the script directly as said before. Don't know what is the difference in practive between both versions though

2022-10-26 13:01 UTC, vitorpmoreira reviewed
Looks good to me, but check the @almeidev comments

2022-10-26 13:30 UTC, afjsilva commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +Invoke-Expression $deployAgent
If I have the original command. We get a ugly exception.
Code test 1:
![image](https://user-images.githubusercontent.com/22283190/198037561-49fd5630-0b01-4681-97d0-b246581a219c.png)
Result test 1:
![image](https://user-images.githubusercontent.com/22283190/198036946-19088046-a04c-4f79-9ab8-79c971a02915.png)

If I try to apply directly the Vitor suggestion. We have an error of 
Code test 2:
![image](https://user-images.githubusercontent.com/22283190/198038129-f3ef9f58-8296-4bf2-aad3-345a14cb85f2.png)

Result test 2:
![image](https://user-images.githubusercontent.com/22283190/198038000-e6d0b8f4-44aa-4319-83e0-5ad13ca1f3f0.png)

Solution and code test 3:
Code test 3:
![image](https://user-images.githubusercontent.com/22283190/198038804-ca7776bd-9497-4048-a206-273558313a0f.png)

Result test 3:
![image](https://user-images.githubusercontent.com/22283190/198038685-4c15872d-ff97-429c-a5fe-ebcc9481ad9d.png)

2022-10-26 13:40 UTC, afjsilva commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +Invoke-Expression $deployAgent
I can change to run the solution 1, is the same than the solution 3 but a little more ugly :D

2022-10-26 15:42 UTC, vitorpmoreira commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +Invoke-Expression $deployAgent
in my solution the first dot has to be removed

2022-10-26 15:51 UTC, almeidev commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +Invoke-Expression $deployAgent
Is there any issue on calling simply `./deployAgent.ps1 -agent $agent`? I think we do not need the _dot sourcing_ or the _call_ operators.

2022-10-26 15:54 UTC, afjsilva commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +Invoke-Expression $deployAgent
you are right. Works if I remove the dot :D

code 2
![image](https://user-images.githubusercontent.com/22283190/198075072-0b67dc7a-d122-4ee0-ba61-adb72d8f1515.png)

result 2
![image](https://user-images.githubusercontent.com/22283190/198074855-6d7af86d-2308-4ed8-af6e-165a67befc0d.png)

2022-10-26 15:56 UTC, vitorpmoreira commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +Invoke-Expression $deployAgent
or without anything and get the error as in the screenshot... :D

2022-10-26 15:56 UTC, afjsilva commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +Invoke-Expression $deployAgent
Ok, I don't know why, but the Invoke-Expression catch/eat the error line from log and only present the message. I think this is the better option, right? What do you think? We can keep the actual solution?

2022-10-26 17:00 UTC, vitorpmoreira commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +Invoke-Expression $deployAgent
Either way sounds good to me. Let's see the opinion of Nuno :)

2022-10-26 17:01 UTC, afjsilva commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +Invoke-Expression $deployAgent
@almeidev 

code (only with one . like @almeidev  said)
![image](https://user-images.githubusercontent.com/22283190/198089091-6b5b7a8d-29b1-4657-b468-ffff1bea37ed.png)

result
![image](https://user-images.githubusercontent.com/22283190/198089016-5c1a1ed0-416f-493f-a30a-e0dc2e76c2fd.png)

2022-10-27 09:21 UTC, almeidev commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +Invoke-Expression $deployAgent
Personally, I try to avoid `Invoke-Expression` unless really necessary (as recommended by the documentation https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-expression).
But either way is fine by my.

2022-10-27 11:35 UTC, afjsilva commented on utils/portal/runInitializeInfrastructureFromTemplate.ps1
> +Invoke-Expression $deployAgent
Updated for a "normal" call/execution of deployAgent.ps1

2022-10-27 11:36 UTC, vitorpmoreira approved these changes

2022-10-27 11:37 UTC, merged