102959 - Kiosk App
criticalmanufacturing/install-scripts pull request #21
Opened 2024-04-02 09:38 UTC by ritanorinho

**Changes**
-Add Kiosk app, Dockerfile and scripts required for first release of MES-in-a-box

2024-04-02 10:31 UTC, afjsilva commented
And  just a remember, the appsettings file used must contain the configuration for the portal where we want to do the login, use the wizard and create the agent.

2024-04-02 12:18 UTC, vitorpmoreira requested changes

2024-04-02 12:18 UTC, vitorpmoreira commented on mesinabox/kioskapp/server.js
> +    const powershell = spawn('pwsh', ['./scriptAfterEnrollment/afterEnrollment.ps1','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJZCI6Ik1FUyIsInRlbmFudE5hbWUiOiJDdXN0b21lclBvcnRhbERFViIsInN1YiI6I
bear in mind that the dev appsettings shouldn't be used afterwards

2024-04-02 12:18 UTC, vitorpmoreira commented on mesinabox/kioskapp/scriptAfterEnrollment/as_agent_test_2_Development_parameters.json
> +  "PROXYHTTPSERVER_AUTHENTICATION_PASSWORD": {
This value is encrypted and only works for the same customer environment (you can't import encrypted parameters between different customer environments). For the time being, it needs to be hard-coded

2024-04-02 12:18 UTC, vitorpmoreira commented on mesinabox/kioskapp/scriptAfterEnrollment/as_agent_test_2_Development_parameters.json
> +  "Portainer_Config_Portainer_Url": "http://test.test",
these portainer parameters can be removed, right?

2024-04-02 12:18 UTC, vitorpmoreira commented on mesinabox/stack/nodetest-deployment.yaml
> +        app.kubernetes.io/managed-by: devopscenter.criticalmanufacturing
the devops center labels are not the case here

2024-04-02 12:18 UTC, vitorpmoreira commented on mesinabox/stack/nodetest-deployment.yaml
> +            cpu: 2
we probably won't need so many resources

2024-04-02 12:18 UTC, vitorpmoreira commented on mesinabox/stack/nodetest-deployment.yaml
> +            cpu: 2
1 cpu and 256 of ram should ne enough, dunno how much node is eating itself, but on our side, we mustn't need a lot

2024-04-02 12:18 UTC, vitorpmoreira commented on mesinabox/stack/nodetest-ingress.yaml
> +    haproxy.router.openshift.io/timeout-tunnel: 0s
The tunnel annotation is not needed here. The other one, I think that we may need to bump it more since we're using the response to send back the logs, so the timeout should be the time that the deployments require. In order to be sure, you can set this to 30seconds, and test the deployment of agent or mes which takes longer than that

2024-04-02 12:18 UTC, vitorpmoreira commented on mesinabox/stack/removeNodeJSStack.ps1
> +oc delete -f nodetest-sa.yaml
this SA doesn't exist

2024-04-02 12:18 UTC, vitorpmoreira commented on mesinabox/stack/DeployNodeJSStack.ps1
> +oc apply --server-side --field-manager=devopscenter.criticalmanufacturing --force-conflicts -f dev.criticalmanufacturing.io-cred.yaml
you're not committing this pull secret, right?

2024-04-02 12:18 UTC, vitorpmoreira commented on mesinabox/stack/nodetest-service.yaml
> +      port: 8081  # port to expose the service. 80?
8081, yes, if we maintain the same SSC as our normal deployments

2024-04-02 13:30 UTC, ritanorinho commented on mesinabox/stack/DeployNodeJSStack.ps1
> +oc apply --server-side --field-manager=devopscenter.criticalmanufacturing --force-conflicts -f dev.criticalmanufacturing.io-cred.yaml
I just added it now, it was missing

2024-04-02 13:38 UTC, ritanorinho commented on mesinabox/stack/nodetest-deployment.yaml
> +            cpu: 2
removed for now

2024-04-02 13:39 UTC, ritanorinho commented on mesinabox/stack/nodetest-deployment.yaml
> +        app.kubernetes.io/managed-by: devopscenter.criticalmanufacturing
done

2024-04-02 13:43 UTC, ritanorinho commented on mesinabox/kioskapp/server.js
> +const server = app.listen(8081, () => {
done

2024-04-02 13:43 UTC, ritanorinho commented on mesinabox/kioskapp/scriptAfterEnrollment/afterEnrollment.ps1
> +Write-Host "PAT: $PAT"
done

2024-04-02 13:44 UTC, ritanorinho commented on mesinabox/kioskapp/scriptAfterEnrollment/as_agent_test_2_Development_parameters.json
> +  "PROXYHTTPSERVER_AUTHENTICATION_PASSWORD": {
done

2024-04-02 13:44 UTC, ritanorinho commented on mesinabox/kioskapp/scriptAfterEnrollment/as_agent_test_2_Development_parameters.json
> +  "Portainer_Config_Portainer_Url": "http://test.test",
done

2024-04-02 13:45 UTC, ritanorinho commented on mesinabox/stack/nodetest-ingress.yaml
> +    haproxy.router.openshift.io/timeout-tunnel: 0s
done

2024-04-02 13:51 UTC, ritanorinho commented on mesinabox/kioskapp/scriptAfterEnrollment/as_agent_test_2_Development_parameters.json
> +  "TRAEFIK_WILDCARD_SSL_KEY_SECRET": {
done

2024-04-02 13:51 UTC, ritanorinho commented on mesinabox/kioskapp/server.js
> +        res.write(`data: ${data}\n\n`);
done

2024-04-02 14:03 UTC, ritanorinho commented on mesinabox/kioskapp/package.json
> +    "nodemon": "^3.1.0",
done

2024-04-02 14:20 UTC, ritanorinho commented on mesinabox/kioskapp/public/client.js
> +  window.location.replace("https://portal.criticalmanufacturing.com/");
done

2024-04-03 08:52 UTC, ritanorinho commented on mesinabox/kioskapp/package.json
> +    "save": "^2.9.0"
done

2024-04-03 09:16 UTC, vitorpmoreira requested changes

2024-04-03 09:16 UTC, vitorpmoreira commented on mesinabox/kioskapp/public/client.js
> +const clusterAddress = window.location;
this should be window.location.origin, because window.location alone will get the entire URL which may contain path, query params, etc

2024-04-03 09:16 UTC, vitorpmoreira commented on mesinabox/kioskapp/Dockerfile
Re-review:

1. The user 1001 nedds to be added to the system.
2. You should have LABELs, then those ENVs, then the ADD, then the RUNs, and finally the COPY, USER+EXPORT and CMD. Although this can be reviewed later since we're getting close to the timeline.
3. When copying stuff from the builder stage or from the context, they need to be chowned by 1001.
4. Why are we installing the dotnet runtime? And wget, nano, curl twice, gzip? Couldn't we install the powershell with microdnf?

2024-04-03 09:17 UTC, vitorpmoreira commented on mesinabox/kioskapp/Dockerfile
https://learn.microsoft.com/en-us/powershell/scripting/install/install-rhel?view=powershell-7.4#installation-via-direct-download

2024-04-03 10:54 UTC, vitorpmoreira commented on mesinabox/kioskapp/Dockerfile
As we've spoken, these changes will be addressed a future iteration

2024-04-03 10:58 UTC, afjsilva commented on mesinabox/kioskapp/Dockerfile
Hey master,
Regarding the powershell, like the URL that you refer, you can do it using the direct download (what we do, using wget) or by package repository (more code). But if you think is better to get from the microsoft repository, I can change it.
Regarding the nano, the idea was to facilitate our lives if we need to edit something on image.
Regarding the curl twice, is wrong and will be fixed.
Regarding gzip, is because we need it to extract the oc. Seems that is necessary to be used on image.

2024-04-03 15:13 UTC, vitorpmoreira reviewed
looks ok for now! waiting for your tests

2024-04-15 09:52 UTC, vitorpmoreira approved these changes

2024-04-15 09:52 UTC, merged