103774 - Kiosk App persists enrollment information
criticalmanufacturing/install-scripts pull request #23
Opened 2024-04-16 15:25 UTC by ritanorinho

**Changes**
- Added YAML files for PV and PVC creation.
- Modified deployment configuration to include the added volume.
- Implemented logic to check for the presence of an agent in the cluster.

2024-04-17 12:09 UTC, vitorpmoreira requested changes

2024-04-17 12:09 UTC, vitorpmoreira commented on mesinabox/kioskapp/server.js
> +        res.write(`data: ${data}\n`);
don't you need to close to the response in the end?

2024-04-17 12:09 UTC, vitorpmoreira commented on mesinabox/kioskapp/server.js
> +        if (data.includes("Stack deployed with Success")) {
you should capture the exit code instead of comparing with logs

2024-04-17 12:09 UTC, vitorpmoreira commented on mesinabox/stack/nodetest-pv.yaml
> +    storageClassName: manual
this one doesn't exist, right? You should set the value to "", so that you don't refer to any storageClass but don't let the system make you use the default one

2024-04-17 15:45 UTC, ritanorinho commented on mesinabox/stack/nodetest-deployment.yaml
> +        securityContext:
yes, i did it according to this documentation https://docs.openshift.com/container-platform/4.8/storage/persistent_storage/persistent-storage-hostpath.html

2024-04-17 15:46 UTC, ritanorinho commented on mesinabox/stack/nodetest-pv.yaml
> +    storageClassName: manual
right

2024-04-17 15:54 UTC, ritanorinho commented on mesinabox/kioskapp/server.js
> +        if (data.includes("Stack deployed with Success")) {
done

2024-04-17 15:55 UTC, ritanorinho commented on mesinabox/kioskapp/server.js
> +        res.write(`data: ${data}\n`);
it is done in exit event

2024-04-17 15:55 UTC, ritanorinho commented on mesinabox/kioskapp/package.json
> +    "fs": "^0.0.1-security"
done

2024-04-18 10:02 UTC, EgzysT approved these changes

2024-04-18 10:07 UTC, vitorpmoreira approved these changes
To be reviewed afterwards

2024-04-18 10:12 UTC, merged