103778 - CMOS App expand disk
criticalmanufacturing/install-scripts pull request #25
Opened 2024-04-24 16:46 UTC by ritanorinho

**Changes**:
- **Create Volume to Use Pipe in VM**: Added functionality to create a volume for using the pipe created in the virtual machine.
- **Resize Largest Physical Volume in VM**: Implemented logic to resize the largest physical volume in the virtual machine
- **Execute Button**: Added a button to execute the above actions.

2024-04-26 17:23 UTC, vitorpmoreira requested changes

2024-04-26 17:23 UTC, vitorpmoreira commented on mesinabox/kioskapp/views/index.html
> +        <button class="cmf-btn" id="expandDiskButton">Expand disk</button>
Disk

2024-04-26 17:23 UTC, vitorpmoreira commented on mesinabox/kioskapp/server.js
> +  const commandToRun = 'pvresize "$(pvdisplay --units b -c | awk -F: \'{print $1,$7}\' | sort -k2 -nr | head -n1 | awk \'{print $1}\')"';
This is missing the commands to setup the disk as well. This feature must setup the disk, if it hasn't been setup yet, OR expand the disk if it was already setup.

2024-04-26 17:23 UTC, vitorpmoreira commented on mesinabox/kioskapp/server.js
> +const { spawn, exec } = require('child_process');
exec is not in use

2024-04-26 17:23 UTC, vitorpmoreira commented on mesinabox/kioskapp/server.js
> +  wstream.close()
we need to collect the exit code and show success or failure to the GUI

2024-04-26 17:23 UTC, vitorpmoreira commented on mesinabox/stack/nodetest-deployment.yaml
> +            path: /etc/resizeDiskPipe            # Path on the host node containing the named pipe
From the linux filesystem, it appears that the named pipe is better placed at the /var/run dir. https://stackoverflow.com/questions/15794696/what-is-the-proper-place-to-put-named-pipes-on-linux

2024-04-29 15:25 UTC, ritanorinho commented on mesinabox/kioskapp/views/index.html
> +        <button class="cmf-btn" id="expandDiskButton">Expand disk</button>
done

2024-04-29 15:30 UTC, ritanorinho commented on mesinabox/kioskapp/server.js
> +const { spawn, exec } = require('child_process');
removed

2024-04-30 12:01 UTC, ritanorinho commented on mesinabox/kioskapp/server.js
> +  const commandToRun = 'pvresize "$(pvdisplay --units b -c | awk -F: \'{print $1,$7}\' | sort -k2 -nr | head -n1 | awk \'{print $1}\')"';
done

2024-05-02 19:15 UTC, vitorpmoreira requested changes

2024-05-02 19:15 UTC, vitorpmoreira commented on mesinabox/kioskapp/public/client.js
> +        body: JSON.stringify({
body is not required

2024-05-02 19:15 UTC, vitorpmoreira commented on mesinabox/kioskapp/public/client.js
> +            throw new Error('Network response was not ok');
We need a better message here. Something like "Failed to expand the disk. Details: {error details here}"

2024-05-02 19:15 UTC, vitorpmoreira commented on mesinabox/kioskapp/server.js
> +            console.log("timed out")
we should send a timeout error to the gui to be presented

2024-05-02 19:15 UTC, vitorpmoreira commented on mesinabox/kioskapp/server.js
> +                res.send(data);
if the output is an error, the res should send the data back with an error, probably 500 and the details of that to be presented in the gui

2024-05-02 19:15 UTC, vitorpmoreira commented on mesinabox/stack/nodetest-sc.yaml
> +reclaimPolicy: Delete
we should set as Retain, so that data from old volumes is not lost

2024-05-03 13:25 UTC, ritanorinho commented on mesinabox/kioskapp/public/client.js
> +        body: JSON.stringify({
done

2024-05-03 13:36 UTC, ritanorinho commented on mesinabox/kioskapp/public/client.js
> +            throw new Error('Network response was not ok');
done

2024-05-03 13:41 UTC, ritanorinho commented on mesinabox/kioskapp/public/client.js
> +        body: JSON.stringify({
done

2024-05-03 13:41 UTC, ritanorinho commented on mesinabox/kioskapp/public/client.js
> +            throw new Error('Network response was not ok');
done

2024-05-03 16:25 UTC, vitorpmoreira approved these changes

2024-05-03 16:57 UTC, merged