Upload Certificate - Catch Errors w/o crashing + disable upload with no file selected
criticalmanufacturing/install-scripts pull request #26
Opened 2024-04-25 20:16 UTC by EgzysT

- Previously, upon submitting an upload, if the upload request errored out for whatever reason, the page would show the default error message instead of handling it.
- Now, the page will catch the error, and display the error message in a small box underneath, which will disappear once the selected file is changed.
- Also, to prevent uploading without any attached file, added guards in both server and client side.

2024-04-26 17:14 UTC, vitorpmoreira requested changes

2024-04-26 17:14 UTC, vitorpmoreira commented on mesinabox/kioskapp/public/upload.js
> +  const errorDiv = document.getElementById('uploadErrorMessage');
Is this API available? If so, it appears to be cleaner - https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceChildren

2024-05-02 09:20 UTC, EgzysT commented on mesinabox/kioskapp/public/upload.js
> +  const errorDiv = document.getElementById('uploadErrorMessage');
Thank you! I applied your suggestion with a small comment since the name is not immediately obvious as to why it's there.

2024-05-02 19:17 UTC, vitorpmoreira requested changes

2024-05-03 15:47 UTC, EgzysT commented on mesinabox/kioskapp/server.js
> +    res.status(500).json({ message: 'Internal server error' });
Now sending error message:
![image](https://github.com/criticalmanufacturing/install-scripts/assets/17938220/815888f6-a2b9-4dc1-9ccc-dcf82ded726a)

2024-05-03 15:49 UTC, EgzysT commented on mesinabox/kioskapp/public/upload.js
> +    // const success = await waitForEndpointUp(data.newEndpoint, 120000)
They have been included in this PR

2024-05-03 16:38 UTC, joseloc300 commented on mesinabox/kioskapp/public/upload.js
> +      throw new Error(data.message);
switch with only 1 case. the last throw could be on the default case since after the break it will always land there. otherwise this switch case could just be an if

2024-05-03 16:38 UTC, joseloc300 commented on mesinabox/kioskapp/server.js
> +  // Allow requests from all origins for now ( TODO: Replace '*' with current domain )
TODO

2024-05-03 16:47 UTC, EgzysT commented on mesinabox/kioskapp/server.js
> +  // Allow requests from all origins for now ( TODO: Replace '*' with current domain )
This is one of those cases where the TODO should stay. The use of wildcard is not recommended as it opens possible security issues, but we thought it was "good enough" for now. It should always use the "current" domain, but changing it upon finished upload was deemed "too much work for now", and we don't know if for sure that is even possible without pod restart.

2024-05-03 18:01 UTC, joseloc300 approved these changes

2024-05-03 18:34 UTC, vitorpmoreira approved these changes

2024-05-03 18:36 UTC, merged