104992 - CMOS App - Check portal and registry connections
criticalmanufacturing/install-scripts pull request #27
Opened 2024-04-29 15:10 UTC by ritanorinho

**Changes**
- Add  logic to check if portal and registry are reachable.
- Replace hardcoded values with environment variables.

2024-04-30 11:16 UTC, vitorpmoreira requested changes

2024-04-30 11:16 UTC, vitorpmoreira commented on mesinabox/kioskapp/public/enroll.js
> +    console.error('Error fetching environment variable:', error);
this error doesn't seem right

2024-04-30 11:16 UTC, vitorpmoreira commented on mesinabox/kioskapp/public/enroll.js
> +    console.error('Error fetching environment variable:', error);
actually it feels like duplicated code that also exists in the client.js

2024-04-30 11:16 UTC, vitorpmoreira commented on mesinabox/stack/nodetest-deployment.yaml
> +          value: "portalqa.criticalmanufacturing.dev"
this should be the set to the prod env

2024-04-30 11:16 UTC, vitorpmoreira commented on mesinabox/kioskapp/server.js
> +  ping.sys.probe(address, function(isAlive) {
Do we really need to rely on this ping package? Can't we just make a GET request to the portal url?

2024-04-30 11:56 UTC, ritanorinho commented on mesinabox/stack/nodetest-deployment.yaml
> +          value: "portalqa.criticalmanufacturing.dev"
for now I prefer to keep these values ​​pointing to the qa portal because we are still doing tests

2024-04-30 11:59 UTC, ritanorinho commented on mesinabox/kioskapp/public/enroll.js
> +    console.error('Error fetching environment variable:', error);
yes, the error is not correct. they are both asking for the portal address, but they are doing different things with it after that

2024-04-30 12:00 UTC, ritanorinho commented on mesinabox/kioskapp/public/enroll.js
> +    console.error('Error fetching environment variable:', error);
fixed

2024-04-30 12:01 UTC, ritanorinho commented on mesinabox/kioskapp/server.js
> +  ping.sys.probe(address, function(isAlive) {
yes, but we need to ping the registry and so I prefer to make the request the same way for both

2024-05-02 10:03 UTC, ritanorinho commented on mesinabox/kioskapp/server.js
> +  ping.sys.probe(address, function(isAlive) {
done

2024-05-02 19:04 UTC, vitorpmoreira requested changes
just a small package require that should be removed

2024-05-02 19:04 UTC, vitorpmoreira commented on mesinabox/kioskapp/server.js
> +const https = require('https');
This can be removed

2024-05-03 10:04 UTC, vitorpmoreira approved these changes

2024-05-03 10:06 UTC, merged