CMOS app polish
criticalmanufacturing/install-scripts pull request #29
Opened 2024-05-08 10:46 UTC by EgzysT

- Connectivity Check is now done every 5~6 seconds. 
  - If the portal or registry connection is lost/recovered, the next check will update the visual representation
  - If one or both of the connections are not working, the "Go To Portal" button will be disabled.
- In the agent installation page, once the installation has succeeded, the "Open in Portal" button now redirects to the infrastructure page correctly.
- If Agent is already installed, show the "Go To Portal" Button which redirects to the Infrastructure page.
- Normalized the appearance of various feedback messages:
  - infra already installed
  - certificate upload file input and progress messages
  - portal connectivity
  - expand disk feedback
- Refactoring:
  - A lot of code changes were just formatting issues (like tabs and lack of ';' at the end of lines)
  - Server connectivity checks are now done in parallel
  - Agent status API fetch and portal address API fetch are now done in parallel

This PR needs a small change in the Customer Portal that will enter in the following PR:

2024-05-08 15:12 UTC, vitorpmoreira requested changes

2024-05-08 15:12 UTC, vitorpmoreira commented on mesinabox/kioskapp/public/client.js
> +  if (agentInstalledData !== "false") {
is this supposed to be a string containing false? why not a boolean?

2024-05-08 15:12 UTC, vitorpmoreira commented on mesinabox/kioskapp/public/upload.js
> +  pollStatusText.innerHTML = `Waiting up to ${pollingTimeoutSeconds} seconds for<br>new domain to be up...`
Just a minor thing:
"... for **the** new ..."

Also applies to the message below, in the interval. Applies to the certTimeoutWaitingProgress method as well, but in this case in in the "... waiting for **the** new deployment ..."

2024-05-08 15:12 UTC, vitorpmoreira commented on mesinabox/kioskapp/server.js
> +    const [portalResponse, registryResponse] = await Promise.allSettled([
The timeouts should be set higher than that, you may be far far away or with networking limitations, like proxies or firewalls. I'd say 5 seconds. For example, in the envmanager, the first test against the Portal has a timeout of 30 seconds. Additionally, we should make use of an environment variable to be able to override these values.

2024-05-08 15:34 UTC, EgzysT commented on mesinabox/kioskapp/public/client.js
> +  if (agentInstalledData !== "false") {
The truth is, the API result is either "false" (it's text because that's what we fetch in the response.text(); in line 136) if there is no agent installed or the string for a json object with the result - example: '{"infraName":"testInfraName","infraId":123}'.

2024-05-08 16:35 UTC, EgzysT commented on mesinabox/kioskapp/public/upload.js
> +  pollStatusText.innerHTML = `Waiting up to ${pollingTimeoutSeconds} seconds for<br>new domain to be up...`
added the "the" to those messages, and moved the line break to better fit the message display

2024-05-09 09:55 UTC, vitorpmoreira commented on mesinabox/kioskapp/public/client.js
> +  if (agentInstalledData !== "false") {
So, shouldn't the response be json and in the case it doesn't exist, its empty?

2024-05-09 09:56 UTC, vitorpmoreira commented on mesinabox/kioskapp/server.js
> +    const [portalResponse, registryResponse] = await Promise.allSettled([
Nice, thank you! Yet, set the default value to 30s as well.

2024-05-09 11:03 UTC, vitorpmoreira requested changes

2024-05-09 11:03 UTC, vitorpmoreira commented on mesinabox/kioskapp/public/client.js
>      const agentJsonData = JSON.parse(agentInstalledData);
Hmm, I think that you had to return response.json() in the handling of the api fetch

2024-05-09 11:03 UTC, vitorpmoreira commented on mesinabox/kioskapp/server.js
>  app.get('/api/agentInstalled', async (req, res) => {
If there's no agent installed, it should return a 404, so that in the GUI you either have a 200 with the agent details or a 404 (or any other error)

2024-05-09 14:28 UTC, vitorpmoreira commented on mesinabox/kioskapp/server.js
>  app.get('/api/agentInstalled', async (req, res) => {
nice, thanks!

2024-05-09 14:29 UTC, vitorpmoreira approved these changes

2024-05-09 14:31 UTC, merged