Add clickhouse helmcharts
criticalmanufacturing/install-scripts pull request #30
Opened 2024-05-08 20:08 UTC by CidHighwindVII

# What was done

Created clickhouse helmcharts

# How to test

- Login into an openshift cluster
- In clickhouse folder run script: helm install clickhousecharttest -n clickhousecharttestnamespace --create-namespace .
- Ask "Carlos Leite" for the console application that makes requests to clickhouse
Bonus: Ask "Vitor Moreira" advice on helmcharts "code smells"

2024-05-14 17:36 UTC, vitorpmoreira requested changes

2024-05-14 17:36 UTC, vitorpmoreira commented on platform/v11.0/OpenShift/Clickhouse/templates/configMaps/config-cfg.yaml
> +        {{- if .Values.kafka.sasl }}
Shouldn't these be if/elses?

2024-05-14 17:36 UTC, vitorpmoreira commented on platform/v11.0/OpenShift/Clickhouse/templates/configMaps/config-cfg.yaml
> +            <!--<formatting>json</formatting>-->
formatter is commented

2024-05-14 17:36 UTC, vitorpmoreira commented on platform/v11.0/OpenShift/Clickhouse/templates/route.yaml
This file is only valid for openshift, doesn't apply for other orchestrators. Additionally, there's no need for a route, you can just use an ingress and the OpenShift will create the Route for it. Having the ingress, it means that is it is valid for other orchestrators as well.

The OpenShift customization, like the termination, can be customized through annotations on the ingress

2024-05-14 17:36 UTC, vitorpmoreira commented on platform/v11.0/OpenShift/Clickhouse/templates/secrets/clickhouse-secrets.yaml
This file doesn't appear to be in use, (unless you modify it locally, which isn't what's supposed to be done) but will be always deployed. Either we support passing the root ca and the cert data for each entry of the secret, or we only allow the existing secret option.

2024-05-14 17:36 UTC, vitorpmoreira commented on platform/v11.0/OpenShift/Clickhouse/templates/security/openshift-nonroot-rb.yaml
This rolebinding only makes sense for openshift as well

2024-05-14 17:36 UTC, vitorpmoreira commented on platform/v11.0/OpenShift/Clickhouse/values.yaml
> +resources: {}
I think that we should have some reference resource limits, at least

2024-05-15 07:17 UTC, CidHighwindVII commented on platform/v11.0/OpenShift/Clickhouse/templates/configMaps/config-cfg.yaml
> +        {{- if .Values.kafka.sasl }}
Not necessarily. There is the argument that if kafka is in the same network there is no need to use client credentials nor username/password. I would keep it like this still.

2024-05-15 07:18 UTC, CidHighwindVII commented on platform/v11.0/OpenShift/Clickhouse/templates/configMaps/config-cfg.yaml
> +            <!--<formatting>json</formatting>-->
I've left it like this on purpose but it's "trash" in the yaml .... I'm going to uncomment it because most of the clients will have a Infrastructure Agent and having logs in json is a "plus".

2024-05-15 07:21 UTC, CidHighwindVII commented on platform/v11.0/OpenShift/Clickhouse/templates/security/openshift-nonroot-rb.yaml
Then it's correct because this charts where created for Openshift :P

2024-05-15 07:25 UTC, jpsfs commented on platform/v11.0/OpenShift/Clickhouse/templates/configMaps/config-cfg.yaml
> +            <!--<formatting>json</formatting>-->
Starting in the next version, we will no longer parse the JSON files. No need to do this.

2024-05-15 07:34 UTC, CidHighwindVII commented on platform/v11.0/OpenShift/Clickhouse/templates/configMaps/config-cfg.yaml
> +            <!--<formatting>json</formatting>-->
Removed formatting.

2024-05-15 07:35 UTC, CidHighwindVII commented on platform/v11.0/OpenShift/Clickhouse/templates/secrets/clickhouse-secrets.yaml
The idea of this file was to somehow "alert" that this secret is required.

2024-05-15 07:41 UTC, CidHighwindVII commented on platform/v11.0/OpenShift/Clickhouse/values.yaml
> +resources: {}
We (cmf) don't have any resource limits reference in clickhouse. The only website I saw that had resources more or less trustworthy was this.

https://towardsdev.com/deploying-clickhouse-on-a-kubernetes-cluster-using-terraform-d4e2234c27af

resources:
  limits:
    memory: 6Gi
  requests:
    cpu: 500m
    memory: 4Gi
    
I will add this in the commented area, bare in mind, that the idea of these scripts is that before executing them the clients give it a look and see if they agree with the "data" there.

2024-05-15 11:54 UTC, vitorpmoreira approved these changes

2024-05-15 13:14 UTC, vitorpmoreira approved these changes

2024-05-15 13:51 UTC, CidHighwindVII commented on platform/v11.0/OpenShift/Clickhouse/templates/secrets/clickhouse-secrets.yaml
> +  root.crt: "Add root.crt here in base64 or create the secret manually in the cluster"
Added char that thorws error if not changed.

2024-05-15 13:51 UTC, CidHighwindVII commented on platform/v11.0/OpenShift/Clickhouse/Chart.yaml
> +description: Critical Manufacturing ClickHouse
Added template to description

2024-05-15 13:51 UTC, CidHighwindVII commented on platform/v11.0/OpenShift/Clickhouse/values.yaml
> +  storageClassName: ocs-storagecluster-cephfs
Not going to change as discussed.

2024-05-15 13:52 UTC, CidHighwindVII commented on platform/v11.0/OpenShift/Clickhouse/values.yaml
> +  pullPolicy: Always
Going to keep Always.

2024-05-15 13:52 UTC, CidHighwindVII commented on platform/v11.0/OpenShift/Clickhouse/templates/configMaps/config-cfg.yaml
> +                <verificationMode>none</verificationMode>
Added a variable so that the user can change the value.

2024-05-15 13:54 UTC, CidHighwindVII commented on platform/v11.0/OpenShift/Clickhouse/templates/configMaps/config-cfg.yaml
> +            <ssl_endpoint_identification_algorithm>none</ssl_endpoint_identification_algorithm>
Added variable that can be used to set that value.

2024-05-15 13:55 UTC, CidHighwindVII commented on platform/v11.0/OpenShift/Clickhouse/values.yaml
> +  defaultPassword: qaz123WSX
No.

2024-05-15 14:14 UTC, miguelnunes94 approved these changes

2024-05-15 15:01 UTC, merged