105023 - Rename CMOS stack resources
criticalmanufacturing/install-scripts pull request #31
Opened 2024-05-09 13:38 UTC by ritanorinho

**Changes**
- Rename CMOS resources.
- Rename files.

2024-05-09 14:10 UTC, vitorpmoreira requested changes

2024-05-09 14:10 UTC, vitorpmoreira commented on mesinabox/stack/deployment.yaml
>      #app.kubernetes.io/version: 11.0.0
we could cleanup the commented lines

2024-05-09 14:10 UTC, vitorpmoreira commented on mesinabox/stack/route.yaml
This route does not include any hostname, is it automatically appended by the system while deploying? Additionally, could we use an ingress instead of the Route since it is manually created by the orchestrator?

2024-05-09 14:10 UTC, vitorpmoreira commented on mesinabox/stack/route.yaml
Additionally, from the deploy/remove scripts, you have:
1. Service
2. Deployment
3. Ingress
4. ClusterRoleBinding
5. PersistentVolumeClaim

The route doesn't exist in this deploy script, and the ingress file doesn't exist in source control since you're deleting it. I'd say that we should have the ingress and not the route.

2024-05-15 14:06 UTC, vitorpmoreira commented on mesinabox/stack/route.yaml
drop the ingress, stick with the route

2024-05-17 11:33 UTC, ritanorinho commented on mesinabox/stack/deployment.yaml
>      #app.kubernetes.io/version: 11.0.0
done

2024-05-17 11:34 UTC, ritanorinho commented on mesinabox/stack/route.yaml
done

2024-05-20 09:35 UTC, vitorpmoreira requested changes

2024-05-20 09:35 UTC, vitorpmoreira commented on mesinabox/stack/deployment.yaml
> +        image: dev.criticalmanufacturing.io/rita/kioskapp:0.0.2
dev.criticalmanufacturing.io/criticalmanufacturing/cmos:1.0.0

2024-05-21 08:10 UTC, ritanorinho commented on mesinabox/stack/deployment.yaml
> +        image: dev.criticalmanufacturing.io/rita/kioskapp:0.0.2
done

2024-05-21 13:46 UTC, vitorpmoreira approved these changes

2024-05-21 13:47 UTC, merged