CMOS - Apply minor fixes to documentation and script
criticalmanufacturing/install-scripts pull request #34
Opened 2024-05-24 08:06 UTC by ritanorinho

**Changes**
- Apply minor fixes to documentation and script.

2024-05-24 12:05 UTC, afjsilva commented on mesinabox/microshiftIsoGeneration/howTo.md
> +            - usb_automation, usb_content_create, kiosk_automation.
add an enter for this new entry appears like a subpoint

2024-05-27 08:46 UTC, ritanorinho commented on mesinabox/microshiftIsoGeneration/howTo.md
> +            - usb_automation, usb_content_create, kiosk_automation.
done

2024-05-28 19:56 UTC, vitorpmoreira requested changes

2024-05-31 15:58 UTC, vitorpmoreira commented
Since this was moved to the Customer Portal, I'm going to close this.

2024-05-31 15:58 UTC, closed without merging